services:
  database:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: crew_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crew-net

  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - crew-net

volumes:
  postgres_data:

networks:
  crew-net:
    driver: bridge

